name: "auto-actions"
description: "Assign, manage milestones, for issues and PRs."
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ${{ github.token }}

runs:
  using: node12
  main: "dist/index.js"
